
C:\Users\Tidhar\PycharmProjects\BuyMeAutomation>python main.py 
Buy Me Automation is running...
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    runAutomation()
  File "main.py", line 31, in runAutomation
    rundriver(link)
  File "main.py", line 58, in rundriver
    runRecieverScreen(driver, email)
  File "main.py", line 157, in runRecieverScreen
    pictureupload.send_keys(os.path.dirname(__file__)+'\Devops_Experts_final_logo-1-300x120.jpg')
  File "C:\Users\Tidhar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\Tidhar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Tidhar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Tidhar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: File not found : \Devops_Experts_final_logo-1-300x120.jpg
  (Session info: chrome=70.0.3538.102)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)

